name: 'Terraform Unit Tests'

on:
  push:

permissions:
  security-events: write # Needed to upload-sarif
  contents: read # Needed to clone repo
  actions: read # Potentially needed for private repositories (see https://github.com/github/codeql-action/issues/2117)

jobs:
    terraform-unit-tests-dev:
        name: 'Terraform Unit Tests - development'
        uses: ./.github/workflows/tf-unit-tests.yml
        with:
            environment: "development"
            location: "eastus"
    terraform-unit-tests-test:
        name: 'Terraform Unit Tests - test'
        uses: ./.github/workflows/tf-unit-tests.yml
        with:
            environment: "test"